name: Duels
main: me.realized.duels.DuelsPlugin
version: @VERSION@
softdepend: [BountyHunters, CombatLogX, CombatTagPlus, Essentials, Factions, LeaderHeads, mcMMO, MVdWPlaceholderAPI, MyPet, PlaceholderAPI, PvPManager, SimpleClans, Vault, WorldGuard, Multiverse-Core]
# Multiverse-Core added as soft-depend due to locations being null when Duels is loaded first.
# Add any world management plugins to softdepend list if arena doesn't load properly in the generated world.
api-version: 1.14

author: Realized
website: https://www.spigotmc.org/resources/duels.20171/
description: An ultimate solution to server owners wanting to create a duel system.

commands:
   duelo:
     description: Enviar, aceitar, ou recusar um pedido de Duelo.
     aliases: [duelar]
   queue:
    description: Join or leave a queue.
    aliases: [q]
   spectate:
     description: Spectate a duel.
     aliases: [spec, x1spec]
   duels:
     description: Administrative command of Duels.
     aliases: [ds]

permissions:
  duels.*:
    children:
      duels.admin: true
  duels.admin:
    children:
      duels.default: true
      duels.stats.others: true
      duels.kits.*: true
      duels.teleport.bypass: true
      duels.spectate: true
      duels.spectate.anonymously: true
      duels.use.*: true
      duels.queue: true
  duels.default:
    children:
      duels.duelo: true
      duels.stats: true
      duels.toggle: true
      duels.top: true
  duels.duelo:
    default: true